spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: eventGroup
      trigger-topic: event-topic
      sender-topic: send-topic
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_db
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
